In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("Original array:", arr1)

add_result = arr1 + 2
print("a) After adding 2:", add_result)

mul_result = arr1 * 3
print("b) After multiplying by 3:", mul_result)

div_result = arr1 / 2
print("c) After dividing by 2:", div_result)

Original array: [1 2 3 4 5]
a) After adding 2: [3 4 5 6 7]
b) After multiplying by 3: [ 3  6  9 12 15]
c) After dividing by 2: [0.5 1.  1.5 2.  2.5]


In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values_x, counts_x = np.unique(x, return_counts=True)
most_frequent_x = values_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_x)[0]
print("i. Array x:", x)
print("Most frequent value:", most_frequent_x)
print("Indices:", indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = values_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]
print("\nii. Array y:", y)
print("Most frequent value:", most_frequent_y)
print("Indices:", indices_y)

i. Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices: [0 5 7 8 9]

ii. Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices: [0 1 2]


In [13]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("2-D array:\n", arr3)

element_a = arr3[0, 1]
print("a) 1st row, 2nd column:", element_a)

element_b = arr3[2, 0]
print("b) 3rd row, 1st column:", element_b)

2-D array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


In [9]:
ucs420_ishan = np.linspace(10, 100, 25)
print("Array:\n", ucs420_ishan)

print("Dimensions (ndim):", ucs420_ishan.ndim)
print("Shape:", ucs420_ishan.shape)
print("Total elements (size):", ucs420_ishan.size)
print("Data type (dtype):", ucs420_ishan.dtype)
print("Total bytes consumed (nbytes):", ucs420_ishan.nbytes)

transposed_reshape = ucs420_ishan.reshape(25, 1)
print("\nTransposed using reshape() -> shape:", transposed_reshape.shape)

transposed_T = ucs420_ishan.T
print("Using .T attribute -> shape:", transposed_T.shape)

Array:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200

Transposed using reshape() -> shape: (25, 1)
Using .T attribute -> shape: (25,)


In [11]:
ucs420_ishan2 = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Array (3x4):\n", ucs420_ishan2)

print("Mean:", np.mean(ucs420_ishan2))
print("Median:", np.median(ucs420_ishan2))
print("Max:", np.max(ucs420_ishan2))
print("Min:", np.min(ucs420_ishan2))
print("Unique elements:", np.unique(ucs420_ishan2))

reshaped_ucs420_ishan2 = ucs420_ishan2.reshape(4, 3)
print("\nReshaped (4x3):\n", reshaped_ucs420_ishan2)

resized_ucs420_ishan2 = ucs420_ishan2.copy()
resized_ucs420_ishan2.resize(2, 3)
print("\nResized (2x3):\n", resized_ucs420_ishan2)

Array (3x4):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3):
 [[10 20 30]
 [40 50 60]]
