In [9]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original temperature readings:", temperature)


corrected_temp = temperature + 2
print("a. Corrected temperatures (+2C):", corrected_temp)


fahrenheit_temp = (9/5) * temperature + 32
print("b. Temperatures in Fahrenheit:", fahrenheit_temp)


above_32 = temperature[temperature > 32]
print("c. Readings greater than 32C:", above_32)


count_above_32 = np.sum(temperature > 32)
print("d. Count of readings exceeding 32C:", count_above_32)


print("e. Vectorization applies operations to the whole array at once using optimized, pre-compiled C loops, avoiding Python's slow per-element loop overhead. Boolean indexing filters elements in a single compiled pass rather than checking each element with an if-condition inside a for loop. Together they make NumPy significantly faster and more memory-efficient than explicit iteration.")

Original temperature readings: [25 28 31 35 38 27 33 40]
a. Corrected temperatures (+2C): [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
c. Readings greater than 32C: [35 38 33 40]
d. Count of readings exceeding 32C: 4
e. Vectorization applies operations to the whole array at once using optimized, pre-compiled C loops, avoiding Python's slow per-element loop overhead. Boolean indexing filters elements in a single compiled pass rather than checking each element with an if-condition inside a for loop. Together they make NumPy significantly faster and more memory-efficient than explicit iteration.


In [11]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Steps matrix:\n", steps)


print("a. Total steps recorded:", np.sum(steps))


print("b. Mean number of steps:", np.mean(steps))


print("c. Maximum steps:", np.max(steps), "| Minimum steps:", np.min(steps))


total_per_day = np.sum(steps, axis=0)
print("d. Total steps per day (axis=0):", total_per_day)


total_per_user = np.sum(steps, axis=1)
print("e. Total steps per user (axis=1):", total_per_user)


max_position_flat = np.argmax(steps)
max_position_2d = np.unravel_index(max_position_flat, steps.shape)
print(f"f. Max steps position -> User {max_position_2d[0]+1}, Day {max_position_2d[1]+1}, Value: {steps[max_position_2d]}")

Steps matrix:
 [[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]
a. Total steps recorded: 84200
b. Mean number of steps: 7016.666666666667
c. Maximum steps: 9500 | Minimum steps: 4500
d. Total steps per day (axis=0): [26500 27300 30400]
e. Total steps per user (axis=1): [18300 24500 14400 27000]
f. Max steps position -> User 4, Day 3, Value: 9500


In [13]:

original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)


subset = original[1:4]
print("b. Subset (index 1 to 4):", subset)


subset[0] = 999
print("c. original:", original, "| subset:", subset)
print("   (original changed too - a basic slice is a VIEW sharing the same memory)")


original = np.array([1, 2, 3, 4, 5, 6])  
subset_copy = original[1:4].copy()
subset_copy[0] = 500
print("d. original:", original, "| subset_copy:", subset_copy)
print("   (original UNCHANGED - .copy() creates independent memory)")


matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("e. 3x4 matrix:\n", matrix_3x4)


print("f. First row:", matrix_3x4[0])
print("   Last row:", matrix_3x4[-1])
print("   Second column:", matrix_3x4[:, 1])
print("   Rows 1-2, columns 2-3:\n", matrix_3x4[1:3, 2:4])

flattened_arr = matrix_3x4.flatten()
raveled_arr = matrix_3x4.ravel()
print("g. flatten():", flattened_arr)
print("   ravel():", raveled_arr)


raveled_arr[0] = -1
print("h. raveled_arr:", raveled_arr)
print("   original after modifying ravel():\n", matrix_3x4)
print("   (original IS affected - ravel() returns a view whenever possible)")


matrix_3x4 = np.arange(1, 13).reshape(3, 4)
flattened_arr = matrix_3x4.flatten()


flattened_arr[0] = -1
print("i. flattened_arr:", flattened_arr)
print("   original after modifying flatten():\n", matrix_3x4)
print("   (original NOT affected - flatten() always returns a copy)")


print("j. Shape:", matrix_3x4.shape, "| ndim:", matrix_3x4.ndim,
      "| size:", matrix_3x4.size, "| dtype:", matrix_3x4.dtype)

a. Original array: [1 2 3 4 5 6]
b. Subset (index 1 to 4): [2 3 4]
c. original: [  1 999   3   4   5   6] | subset: [999   3   4]
   (original changed too - a basic slice is a VIEW sharing the same memory)
d. original: [1 2 3 4 5 6] | subset_copy: [500   3   4]
   (original UNCHANGED - .copy() creates independent memory)
e. 3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. First row: [1 2 3 4]
   Last row: [ 9 10 11 12]
   Second column: [ 2  6 10]
   Rows 1-2, columns 2-3:
 [[ 7  8]
 [11 12]]
g. flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
h. raveled_arr: [-1  2  3  4  5  6  7  8  9 10 11 12]
   original after modifying ravel():
 [[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   (original IS affected - ravel() returns a view whenever possible)
i. flattened_arr: [-1  2  3  4  5  6  7  8  9 10 11 12]
   original after modifying flatten():
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
   (original NOT affected - flatten() 

In [17]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])


print("a. Shape of X:", X.shape, "| Dimensions (ndim):", X.ndim)


X_T = X.T
print("b. X.T:\n", X_T)
print("   Explanation: transpose flips rows/columns - each row of X.T now represents")
print("   one FEATURE (sleep, activity, stress) across all 4 users.")


XtX = X_T @ X
print("c. X.T @ X:\n", XtX)


XtX_inv = np.linalg.inv(XtX)
print("d. Inverse of (X.T @ X):\n", XtX_inv)


beta = XtX_inv @ X_T @ y
print("e. OLS coefficients (beta):", beta)


print("f. Each coefficient represents the change in predicted assistance score for a one-unit increase in that feature (sleep, activity, stress), holding the other two features fixed.")


new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("g. Predicted assistance score for new_user:", predicted_score)

a. Shape of X: (4, 3) | Dimensions (ndim): 2
b. X.T:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
   Explanation: transpose flips rows/columns - each row of X.T now represents
   one FEATURE (sleep, activity, stress) across all 4 users.
c. X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
d. Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
e. OLS coefficients (beta): [-0.15921454  0.14083853 10.06302242]
f. Each coefficient represents the change in predicted assistance score for a one-unit increase in that feature (sleep, activity, stress), holding the other two features fixed.
g. Predicted assistance score for new_user: 75.27862544779117
